catalogo/urls.py
from django.urls import path, re_path, include
from . import views
app_name = 'catalogo'

urlpatterns = [
    re_path(r'^$', views.list_categorias_iniciais, name='list_categorias_iniciais'),
    re_path(r'(?P<categoria_id>^\d{2,20}$)', views.list_categorias, name='list_categorias'),
    re_path(r'^config_integration$', views.detail_config_integration, name='detail_config_integration'),

    re_path(r'^config_categoria/(?P<categoria_id>\d+)', views.detail_config_categoria, name='detail_config_categoria'),
    re_path(r'^create_config_categoria', views.create_config_categoria, name='create_config_categoria'),
    re_path(r'^delete_config_categoria/(?P<categoria_id>\d+)', views.delete_config_categoria, name='delete_config_categoria'),
    re_path(r'^list_config_categoria', views.list_config_categoria, name='list_config_categoria'),

    re_path(r'^config_propriedade/(?P<prop_id>\d+)', views.detail_config_propriedade, name='detail_config_propriedade'),
    re_path(r'^create_config_propriedade', views.create_config_propriedade, name='create_config_propriedade'),
    re_path(r'^delete_config_propriedade/(?P<prop_id>\d+)', views.delete_config_propriedade, name='delete_config_propriedade'),
    re_path(r'^list_config_propriedade', views.list_config_propriedade, name='list_config_propriedade'),

    re_path(r'^carrega_categorias', views.carrega_categorias),
    re_path(r'^deleta_categorias', views.deleta_categorias)
]

itsm/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'catalogo/', include('catalogo.urls')),
    path('', RedirectView.as_view(url='/catalogo/', permanent=True) )
]

catalogo/models.py
from django.db import models


class AbstractEntity(models.Model):
    ''' Infomações e campos comuns para as classes.
    '''
    nome = models.CharField(max_length=200, name='nome')
    last_date_mod = models.DateTimeField(auto_now=True, \
        verbose_name='Data de alteração')
    created_date = models.DateTimeField(auto_now_add=True, \
        verbose_name='Data de criação')

    class Meta:
        abstract = True
        ordering = ['nome']

    def __str__(self):
        return self.nome
        
class Categoria(AbstractEntity):
    '''
    Define as categorias de serviço ITSM. As categoria são organizadas de forma \
    hierarquica. Categorias finais, são categorias que definem o serviço e que \
    tem o persid da categoria do CA SDM.
    '''
    icone = models.CharField(max_length=20, blank=True)
    figure = models.CharField(max_length=200, blank=True)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, \
        blank=True, null=True)
    in_flag = models.BooleanField(default=False, help_text='É valido para incidente?', \
        verbose_name='Incidente?')
    cr_flag = models.BooleanField(default=False, help_text='É valido para solicitação?', \
        verbose_name='Solicitação?')
    descricao = models.TextField(blank=True, null=True)
    grupo_ca = models.CharField(max_length=70, blank=True, null=True,\
        help_text="Grupo de atendimento no CA SDM")
    persid_pcat_ca = models.CharField(max_length=20, blank=True, null=True, \
        verbose_name='Categoria CA', help_text="Persid da categoria CA SDM")
    script = models.CharField(max_length=255, blank=True, null=True, \
        verbose_name='script', help_text="Script de automação da categoria")

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("catalogo:detail_config_categoria", args=[str(self.id)] )
    
class Propriedade(AbstractEntity):
    '''
    Classe que define as propriedades de uma categoria de serviço. São os \
    campos adicionais no formulário web.
    '''
    nome = models.CharField(max_length=100, unique=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    obrigatorio = models.IntegerField(default=0)
    propriedade_pai = models.ForeignKey('self', on_delete=models.SET_NULL, \
        blank=True, null=True)
    LISTA_TIPO = ( 
    ('str', 'Texto'), 
    ('num','Número'),
    ('dta', 'Data'),
    ('eml', 'Email'),
    ('chk', 'Checkbox')
    )
    tipo = models.CharField(max_length=3, choices=LISTA_TIPO)
    tamanho = models.IntegerField(default=1)
    ordernacao = models.IntegerField(help_text='Define a ordem de exibição do \
        campo no formulário de chamado', verbose_name="Ordenação do campo")

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("catalogo:detail_config_propriedade", args=[str(self.id)])
    
    class Meta:
        ordering = ['ordernacao']

class Config(models.Model):
    '''
        Define as configurações de integração com o CASDM via REST. Define\
        também as configuraçõe de integração com AD.
    '''
    nome = models.CharField(max_length=200, name='nome', default="Configuração")
    CA_host = models.CharField(max_length=50, verbose_name='CA Host')
    CA_port = models.IntegerField(default=8050, verbose_name='CA Porta')
    CA_username = models.CharField(max_length=50, default=None, verbose_name='CA Username')
    CA_password = models.CharField(max_length=50, default=None, verbose_name='CA Password')
    LISTA_HTTP = (
     ('http://', 'http'),
    ('https://', 'https')
    )
    CA_conn = models.CharField(max_length=10, choices=LISTA_HTTP, default="http", verbose_name='CA Procotolo')
    LDAP_username = models.CharField(max_length=50, default=None, verbose_name='LDAP Username')
    LDAP_password = models.CharField(max_length=50, default=None, verbose_name='LDAP Passowrd')
    LDAP_DN = models.CharField(max_length=100, default=None, verbose_name='LDAP DN')
    last_date_mod = models.DateTimeField(auto_now=True, verbose_name='Última data de alteração')
    
    def ca_url_endpoint(self):
        return "%s%s:%s/rest_access/" % (tipo, host, port)

    class Meta:
        verbose_name = 'Configuração'

    def __str__(self):
        return self.nome


# class LogIntegracao(models.Model):
#     LISTA_ACAO = ( 
#     ('post', 'Criação de registro'), 
#     ('put','Atualização de registro'),
#     )
#     acao = models.CharField(choices=LISTA_ACAO)
#     body = models.textField()
#     usuario = models.CharField(max_length=200)
#     created_date = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.acao

catalogo/forms.py
from django.forms import ModelForm
from django import forms
from .models import Propriedade, Categoria, Config

class BaseForm(ModelForm):
    def __init__(self, *args, **kwargs):
            super(BaseForm, self).__init__(*args, **kwargs)
            # Superclasse adiconada, caso os campos não sejam declarados, aplica um stilo de CSS básico.
            for field_name, field in self.fields.items():
                if type(field) == forms.CharField:
                    field.widget.attrs['class'] = 'w3-input w3-border'

class FormPropriedade(BaseForm):
    class Meta:
        model = Propriedade
        fields = '__all__'

class FormCategoria(ModelForm):
    nome = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control' }))
    parent = forms.ModelChoiceField(queryset=Categoria.objects.all(), label = 'Categoria Pai', widget=forms.Select(attrs={'class': 'form-control'} ), required=False)
    icone = forms.CharField(label="Ícone:", widget=forms.TextInput(attrs={'class': 'form-control' }), required=False, max_length = 100 )
    figure = forms.CharField(label="Figura", widget=forms.TextInput(attrs={'class': 'form-control' }), required=False, max_length = 100 )
    in_flag = forms.BooleanField(label='Incidente?', widget=forms.CheckboxInput(attrs={'class': 'form-check'} ), required=False)
    cr_flag = forms.BooleanField(label='Solicitação?', widget=forms.CheckboxInput(attrs={'class': 'form-check'} ), required=False)
    descricao = forms.CharField(label='Descrição', widget=forms.Textarea(attrs={'rows': 5, 'cols': 30, 'class': 'form-control'}), required=False )
    grupo_ca = forms.CharField(label = 'Grupo CA',widget=forms.TextInput(attrs={'class': 'form-control' } ), required=False, max_length = 70 )
    persid_pcat_ca = forms.CharField( label='Categoria Persid CA',widget=forms.TextInput(attrs={'class': 'form-control' } ), required=False, max_length = 20 )
    script = forms.CharField(label='Script automação',widget=forms.TextInput(attrs={'class': 'form-control' } ), required=False, max_length = 255 )
    
    # Classe meta servirá neste caso para exibir no form campos não especificados acima.
    class Meta:
        model = Categoria
        fields = '__all__'
        localized_fields  = '__all__'
        


class FormConfig(BaseForm):
    class Meta:
        model = Config
        fields = '__all__'

catalogo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
from .models import Categoria, Propriedade, Config
from .forms import FormCategoria, FormPropriedade, FormConfig

def list_categorias_iniciais(request):
    '''
    View para index do catálogo comas categorias que não tem pais.
    '''
    categorias_retornadas = Categoria.objects.filter(parent__isnull=True)
    dados = {"categorias" : categorias_retornadas }
    return render(request, 'catalogo/index.html', dados)

def list_categorias(request, categoria_id):
    '''
    View para categorias filhas da categoria pai informada no argumento categoria_id.
    '''
    categorias_retornadas = Categoria.objects.filter(parent__id=categoria_id)
    dados = {"categorias" : categorias_retornadas }
    if categorias_retornadas.count() > 0:
        return render(request, 'catalogo/index.html', dados )
    else:
        propriedades_retornadas = Propriedade.objects.filter(categoria=categoria_id)
        dados = {"propriedades" : propriedades_retornadas }
        return render(request, 'catalogo/detail_cr.html', dados )

###### Detail da configuração de integração
def detail_config_integration(request):
    try:
        config_instanced = Config.objects.get(nome='DEFAULT')
    except Config.DoesNotExist:
        raise Http404("Configuração não encontrada.")
    if request.method == 'POST':
        form = FormConfig(request.POST, instance=config_instanced)
        if form.is_valid():
            form.save()
            return redirect('/')
    elif request.method == 'GET':
        form = FormConfig(instance=config_instanced)
        form = {"form" : form }
        return render(request, 'catalogo/detail_config_integration.html', form)


###### View da configuração de categoria
def list_config_categoria(request):
    try:
        categorias_retornadas = Categoria.objects.all()
        dados = {"form" : FormCategoria, "categorias" : categorias_retornadas}
        return render(request, 'catalogo/list_config_categoria.html', dados )
    except Categoria.DoesNotExist:
        raise Http404("Falha ao recuperar registros no banco de dados.")

def detail_config_categoria(request, categoria_id):
    ''' Função para ver, atualizar ou deletar uma categoria.
    '''
    try:
        categoria_instanced = Categoria.objects.get(pk=categoria_id)
    except Categoria.DoesNotExist:
        raise Http404("Registro de categoria não existe.")
    # para atualizar
    if request.method == 'POST':
        form = FormCategoria(request.POST, instance=categoria_instanced)
        if form.is_valid():
            form.save()
            return redirect("catalogo:list_config_categoria" )
    # Para get
    elif request.method == 'GET':
        form =  FormCategoria(instance=categoria_instanced)
        dados = {"form" : form, "categoria_id" : categoria_id }
        return render(request, 'catalogo/detail_config_categoria.html', dados)


def create_config_categoria(request):
    if request.method == 'POST':
        form = FormCategoria(request.POST)
        if form.is_valid():
            form.save()
            return redirect("catalogo:list_config_categoria")
    elif request.method == 'GET':
        form = FormCategoria
        dados = {"form" : form}
        return render(request, 'catalogo/create_config_categoria.html', dados)

def delete_config_categoria(request, categoria_id):
    ''' Função para deletar uma categoria.
    '''
    try:
        categoria_instanced = Categoria.objects.get(pk=categoria_id)
    except Categoria.DoesNotExist:
        raise Http404("Registro de categoria não existe.")
    # para atualizar
    if request.method == 'POST':
        categoria_instanced.delete()
        return redirect("catalogo:list_config_categoria" )

###### View da configuração de propriedade
def list_config_propriedade(request):
    propriedades_retornadas = Propriedade.objects.all()
    form = FormPropriedade
    dados = {"form" : form, "propriedades" : propriedades_retornadas}
    return render(request, 'catalogo/list_config_propriedade.html', dados )

def detail_config_propriedade(request, prop_id):
    try:
        prop_instanced = Propriedade.objects.get(pk=prop_id)
    except Categoria.DoesNotExist:
        raise Http404("Registro de categoria não existe.")
    if request.method == 'POST':
        form = FormPropriedade(request.POST, instance=prop_instanced)
        if form.is_valid():
            form.save()
            return redirect('catalogo:list_config_propriedade')
    elif request.method == 'GET':
        form = FormPropriedade(instance=prop_instanced)
        dados = {'form' : form, 'prop_id' : prop_id}
        return render(request, 'catalogo/detail_config_propriedade.html', dados)

def create_config_propriedade(request):
    if request.method == 'POST':
        form = FormPropriedade(request.POST)
        if form.is_valid():
            form.save()
            return redirect("catalogo:list_config_propriedade")
    elif request.method == 'GET':
        form = FormPropriedade
        return render(request, 'catalogo/create_config_propriedade.html', {"form" : form})

def delete_config_propriedade(request, prop_id):
    ''' Função para deletar uma categoria.
    '''
    try:
        prop_instanced = Propriedade.objects.get(pk=prop_id)
    except Propriedade.DoesNotExist:
        raise Http404("Registro da propriedade não existe.")
    if request.method == 'POST':
        prop_instanced.delete()
        return redirect("catalogo:list_config_propriedade" )


def detail_cr(request, categoria_id):
    '''
    Tela de abertura de chamado
    '''
    return render(request, 'catalogo/detail_cr.html')

def carrega_categorias(request):
 
    from os import getcwd, path
    print(__file__)
    print(path.abspath(__file__))
    print(path.dirname(path.abspath(__file__)))
    return
    '''
    Função para carregar as categorias usando csv
    '''
    path = 'C:\\Users\\matheus.santana\\OneDrive - MICROCITY\\mypython\\itsm\\csv\\'
    arquivo = 'carga_catalogo.csv'
    path_full = path + arquivo  
    import csv
    from sys import exc_info
    try:
        with open (path_full, encoding='utf-8-sig') as f:
            reader = csv.reader(f, delimiter = ';')
            line_count = 0
            for row in reader:
                if line_count == 0:
                    line_count += 1
                    continue
                if row[0] and not row[2]:
                    object_temp = None
                    object_temp = Categoria(
                        nome = row[0],
                        icone = row[1],
                        parent = None,
                        in_flag = row[3],
                        cr_flag = row[4],
                        grupo_ca  = row [5],
                        id_ca = row[6],
                        script=row[7],
                        servico_final_flag = row[8]
                    )
                else:
                    ins_parent = Categoria.objects.get(nome=row[2])
                    object_temp = None
                    object_temp = Categoria(
                        nome = row[0],
                        icone = row[1],
                        parent = ins_parent,
                        in_flag = row[3],
                        cr_flag = row[4],
                        grupo_ca  = row [5],
                        id_ca = row[6],
                        script=row[7],
                        servico_final_flag = row[8]
                    )
                try:
                    object_temp.save()
                except Exception as e:
                    print(exc_info()[1])
                    print(e)
                finally:
                    line_count += 1
        categoria_inseridas = ", </BR>".join(cat.nome for cat in Categoria.objects.all())
        return HttpResponse('Carga de categorias realizada com sucesso: </BR>' +  categoria_inseridas)
    except Exception as e:
        print(exc_info()[1])
        return HttpResponse('Falha ao ler arquivo CSV: %s. Erro %s' % (arquivo, str(exc_info()[1])))

def deleta_categorias(request):
    from sys import exc_info
    from time import sleep
    try:
        categoria_deleta = ", </BR>".join(cat.nome for cat in Categoria.objects.filter(parent__isnull=False))
        Categoria.objects.filter(parent__isnull=False).delete()
        Categoria.objects.filter(parent__isnull=True).delete()
        return HttpResponse('Categorias deletas do banco de dados com sucesso: <BR>' + categoria_deleta)
    except Exception as e:
        return HttpResponse('Falha deletar categorias, erro: %s' % (str(exc_info()[1])) )

templates/catalogo/base.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    {% comment %} <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> {% endcomment %}
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/w3.css' %}">
    <script src="https://kit.fontawesome.com/819dcc4a7a.js" crossorigin="anonymous"></script>
    <title> {% block title %} {% endblock  %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark" style='box-shadow: 0 0 15px 0 #888888'>
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/catalogo">Catalogo de Serviço</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle btn" href="#" id="navbardrop" data-toggle="dropdown">
                            Configuração do Catálogo
                        </a>
                        <div class="dropdown-menu dropdown-menu-center">
                            <a class="dropdown-item" href="{% url 'catalogo:list_config_categoria' %}">Categoria</a>
                            <a class="dropdown-item" href="{% url 'catalogo:list_config_propriedade' %}" role="button">Propriedade</a>
                            <a class="dropdown-item" href="{% url 'catalogo:detail_config_integration' %}" role="button">Integração</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn" href="/catalogo/importacao">Importação de dados</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block main %} {% endblock %}

    {% comment %} <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> {% endcomment %}
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script> {% endcomment %}
    {% comment %} <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> {% endcomment %}
    <script src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static '/js/bootbox.all.js' %}"></script>
</body>

</html>

templates/catalogo/create_config_categoria.html
{% extends 'catalogo/base.html' %} 
{% block  title %} Catalogo de serviço - criar Categoria{% endblock  %}
{% block main%}
{% load static %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif%}
<main>
    <div class="container-fluid">
        <div class="container py-5 bg-light">
            <form action="{% url 'catalogo:create_config_categoria' %}" method="POST" class="form-group">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.errors }}
                            <label for="{{field.id_for_label}}"> {{ field.label }} </label> 
                            {{ field }}
                        </div>
                    {% endfor %}
                <input type="submit" class="w3-button w3-green w3-round" value="Salvar">
            </form>
        </div>
    </div>
</main>
{% endblock %}

templates/catalogo/create_config_propriedade.html
{% extends 'catalogo/base.html' %} 
{% block  title %} Catalogo de serviço - criar Propriedade{% endblock  %}
{% block main%}
{% load static %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif%}
<main>
    <div class="container-fluid">
        <div class="container py-5 bg-light">
            <form action="{% url 'catalogo:create_config_propriedade' %}" method="POST" class="form-group">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.errors }}
                            <label for="{{field.id_for_label}}"> {{ field.label }} </label> 
                            {{ field }}
                        </div>
                    {% endfor %}
                <input type="submit" class="w3-button w3-green w3-round" value="Salvar">
            </form>
        </div>
    </div>
</main>
{% endblock %}

templates/catalogo/detail_config_integration.html
{% extends 'catalogo/base.html' %} 
{% block  title %} Catalogo de serviço - Configuração CA{% endblock  %}
{% block main%}
{% load static %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif%}
<main>
    <div class="container py-5 bg-light">
            <form action= "{% url 'catalogo:detail_config_integration' %}" method="POST" class="form-group">
                    {% csrf_token %}
                   {% for field in form %}
                        <div class="form-group">
                            {{ field.errors }}
                            <label for="{{field.id_for_label}}"> {{ field.label }} </label> 
                            {{ field }}
                        </div>
                    {% endfor %} 
                <input type="submit" class="w3-button w3-green w3-round" value="Salvar">
            </form>
        </div>
    </div>
</main>
{% endblock %}

templates/catalogo/detail_config_propriedade.html
{% extends 'catalogo/base.html' %} 
{% block  title %} Catalogo de serviço - Propriedades{% endblock  %}
{% block main%}
{% load static %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif%}
<main>
    <div class="container-fluid">
        <div class="container py-5 bg-light">
            <form action="{% url 'catalogo:detail_config_propriedade' prop_id %}" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.errors }}
                            <label for="{{field.id_for_label}}"> {{ field.label }} </label> 
                            {{ field }}
                            {% comment %} {% if field.help_text %}
                                <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %} {% endcomment %}
                        </div>
                    {% endfor %}
                <input type="submit" class="w3-button w3-green w3-round" value="Salvar">
            </form>
            <form action="{% url 'catalogo:delete_config_propriedade' prop_id %}" method="POST" class="form-group">
                {% csrf_token %}
                <input type="submit" class="w3-button w3-red w3-round" value="Deletar">
            </form>
        </div>
    </div>
</main>
{% endblock %}

templates/catalogo/list_config_categoria.html
{% extends 'catalogo/base.html' %} 
{% block  title %} Catalogo de serviço - Configuração Categorias {% endblock  %}
{% block main%}
{% load static %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
 
<main>
    <div class="container-fluid mt-4">
        <table class="w3-table-all w3-striped w3-small w3-centered">
            <thead>
                <tr class="w3-dark-gray w3-center w3-medium">
                    <th scope="col">Nome</th>
                    <th scope="col">Categoria pai</th>
                    <th scope="col">CA ID</th>
                    <th scope="col">Incidente?</th>
                    <th scope="col">Solicitação?</th>
                    <th scope="col">Ícone</th>
                    <th scope="col">Figura</th>
                    <th scope="col">Grupo</th>
                    <th scope="col"> <a name="create_categoria" id="create_categoria" class="w3-button w3-teal" href="{% url 'catalogo:create_config_categoria' %}" role="button">Criar +</a></th>
                </tr>
            </thead>
            <tbody>
                {% for categoria  in categorias %}
                <tr>
                    <td>{{ categoria.nome }}</td>
                    <td>{{ categoria.parent.nome }}</td>
                    <td>{{ categoria.ca_id }}</td>
                    {% if  categoria.in_flag == True %}<td> Sim </td> {% else %} <td> Não </td> {% endif %}
                    {% if  categoria.cr_flag == True %}<td> Sim </td> {% else %} <td> Não </td> {% endif %}
                    <td>{{ categoria.icone}}</td>
                    <td>{{ categoria.figure}}</td>
                    {% if  categoria.grupo_ca %}<td> {{ categoria.grupo_ca}} </td> {% else %} <td>  </td> {% endif %}
                    {% comment %} <td> <a class="btn btn-success" href="{% url 'catalogo:detail_config_categoria' categoria.id %}" role="button">Editar</a> </td> {% endcomment %}
                    <td> <a name="edit_categoria_{{categoria.id}}" id="edit_categoria_{{categoria.id}}" class="w3-button w3-teal" href="{{ categoria.get_absolute_url }}" role="button">Editar</a> </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

templates/catalogo/list_config_propriedade.html
{% extends 'catalogo/base.html' %} 
{% block  title %} Catalogo de serviço - Configuração Categorias{% endblock  %}
{% block main%}
{% load static %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif%}
<main>
    <div class="container-fluid mt-4">
        <table class="w3-table-all w3-striped w3-small w3-centered">
            <thead>
                <tr class="w3-dark-gray w3-center w3-medium">
                    <th scope="col">Nome da propriedade </th>
                    <th scope="col">Categoria relacionada</th>
                    <th scope="col">Obrigatório?</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Propriedade pai</th>
                    <th scope="col">Tamanho </th>
                    <th scope="col"> <a name="create_prop" id="create_prop" class="w3-button w3-teal" href="{% url 'catalogo:create_config_propriedade' %}" role="button">Criar +</a></th>
                </tr>
            </thead>
            <tbody>
                {% for propriedade  in propriedades %}
                <tr>
                    <td>{{ propriedade.nome }}</td>
                    <td>{{ propriedade.categoria }}</td>
                    <td>{{ propriedade.obrigatorio }}</td>
                    <td>{{ propriedade.tipo }}</td>
                    <td>{{ propriedade.propriedade_pai.nome}}</td>
                    <td>{{ propriedade.tamanho}}</td>
                    <td> <a class="w3-button w3-teal" href="{{ propriedade.get_absolute_url }}" role="button">Editar</a> </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}